/**
 * Resume API Route
 * 
 * GET /api/placement/resume - Get user's resume
 * PUT /api/placement/resume - Update resume
 */

import { NextResponse } from 'next/server';
import { requireRole } from '@/lib/auth/guards.js';
import { getResume, upsertResume, updateResume } from '@/lib/db/placement/resumes.js';

/**
 * GET /api/placement/resume
 * Get the active resume for the authenticated user
 */
export async function GET(request) {
  try {
    const session = await requireRole(request, ['student', 'alumni']);
    const userId = session.user.id;
    
    const resume = await getResume(userId);
    
    if (!resume) {
      return NextResponse.json({
        success: true,
        data: null,
        message: 'No resume found. Generate one to get started.'
      });
    }
    
    return NextResponse.json({
      success: true,
      data: resume
    });
  } catch (error) {
    console.error('Error getting resume:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Failed to get resume'
      },
      { status: error.status || 500 }
    );
  }
}

/**
 * PUT /api/placement/resume
 * Update or create resume
 * 
 * Body:
 * {
 *   templateId?: string,
 *   resumeData: object,
 *   isAutoGenerated?: boolean
 * }
 */
export async function PUT(request) {
  try {
    const session = await requireRole(request, ['student', 'alumni']);
    const userId = session.user.id;
    const body = await request.json();
    
    const { templateId, resumeData, isAutoGenerated = false } = body;
    
    // Validation
    if (!resumeData || typeof resumeData !== 'object') {
      return NextResponse.json(
        { success: false, error: 'resumeData is required and must be an object' },
        { status: 400 }
      );
    }

    if (templateId && (typeof templateId !== 'string' || templateId.trim() === '')) {
      return NextResponse.json(
        { success: false, error: 'templateId must be a valid string if provided' },
        { status: 400 }
      );
    }

    if (typeof isAutoGenerated !== 'boolean') {
      return NextResponse.json(
        { success: false, error: 'isAutoGenerated must be a boolean' },
        { status: 400 }
      );
    }
    
    // Check if resume exists
    const existingResume = await getResume(userId);
    
    let resume;
    if (existingResume) {
      // Update existing resume
      resume = await updateResume(existingResume.id, userId, {
        resumeData,
        templateId
      });
    } else {
      // Create new resume
      resume = await upsertResume(userId, {
        templateId: templateId || 'modern',
        resumeData,
        isAutoGenerated
      });
    }
    
    return NextResponse.json({
      success: true,
      data: resume,
      message: 'Resume saved successfully'
    });
  } catch (error) {
    console.error('Error updating resume:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Failed to update resume'
      },
      { status: error.status || 500 }
    );
  }
}
