/**
 * Resumes Database Utilities
 * 
 * Provides CRUD operations for student resumes.
 * 
 * @module db/placement/resumes
 */

import { query, getClient } from '../index.js';

/**
 * Get active resume for a user
 * @param {string} userId - User UUID
 * @returns {Promise<Object|null>} Resume object or null
 */
export async function getResume(userId) {
  const result = await query(
    `SELECT * FROM resumes 
    WHERE user_id = $1 AND is_active = true
    ORDER BY created_at DESC
    LIMIT 1`,
    [userId]
  );
  
  if (result.rows.length === 0) {
    return null;
  }
  
  return mapResumeRow(result.rows[0]);
}

/**
 * Get resume by ID
 * @param {string} resumeId - Resume UUID
 * @param {string} userId - Optional user ID for authorization
 * @returns {Promise<Object|null>} Resume object or null
 */
export async function getResumeById(resumeId, userId = null) {
  let queryStr = `SELECT * FROM resumes WHERE id = $1`;
  const params = [resumeId];
  
  if (userId) {
    queryStr += ` AND user_id = $2`;
    params.push(userId);
  }
  
  const result = await query(queryStr, params);
  
  if (result.rows.length === 0) {
    return null;
  }
  
  return mapResumeRow(result.rows[0]);
}

/**
 * Create or update resume
 * @param {string} userId - User UUID
 * @param {Object} resumeData - Resume data
 * @param {string} resumeData.templateId - Template ID
 * @param {Object} resumeData.resumeData - Structured resume data (JSONB)
 * @param {boolean} resumeData.isAutoGenerated - Is auto-generated
 * @returns {Promise<Object>} Resume object
 */
export async function upsertResume(userId, resumeData) {
  const { templateId = 'modern', resumeData: data, isAutoGenerated = false } = resumeData;
  
  const client = await getClient();
  
  try {
    await client.query('BEGIN');
    
    // Deactivate existing active resume
    await client.query(
      `UPDATE resumes SET is_active = false WHERE user_id = $1 AND is_active = true`,
      [userId]
    );
    
    // Get next version number
    const versionResult = await client.query(
      `SELECT COALESCE(MAX(version), 0) + 1 as next_version
      FROM resumes WHERE user_id = $1`,
      [userId]
    );
    const nextVersion = parseInt(versionResult.rows[0].next_version);
    
    // Create new resume
    const result = await client.query(
      `INSERT INTO resumes (
        user_id, template_id, resume_data,
        is_auto_generated, is_active, version,
        generated_at, last_modified_at
      ) VALUES ($1, $2, $3, $4, true, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      RETURNING *`,
      [
        userId,
        templateId,
        JSON.stringify(data),
        isAutoGenerated,
        nextVersion
      ]
    );
    
    await client.query('COMMIT');
    
    return mapResumeRow(result.rows[0]);
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

/**
 * Update resume data
 * @param {string} resumeId - Resume UUID
 * @param {string} userId - User UUID (for authorization)
 * @param {Object} updates - Fields to update
 * @param {Object} updates.resumeData - Updated resume data
 * @param {string} updates.templateId - Template ID
 * @returns {Promise<Object>} Updated resume object
 */
export async function updateResume(resumeId, userId, updates) {
  const { resumeData: data, templateId } = updates;
  
  const updateFields = [];
  const params = [];
  let paramIndex = 1;
  
  if (data) {
    updateFields.push(`resume_data = $${paramIndex}`);
    params.push(JSON.stringify(data));
    paramIndex++;
    updateFields.push(`last_modified_at = CURRENT_TIMESTAMP`);
  }
  
  if (templateId) {
    updateFields.push(`template_id = $${paramIndex}`);
    params.push(templateId);
    paramIndex++;
  }
  
  if (updateFields.length === 0) {
    throw new Error('No fields to update');
  }
  
  params.push(resumeId, userId);
  const result = await query(
    `UPDATE resumes 
    SET ${updateFields.join(', ')}, updated_at = CURRENT_TIMESTAMP
    WHERE id = $${paramIndex} AND user_id = $${paramIndex + 1}
    RETURNING *`,
    params
  );
  
  if (result.rows.length === 0) {
    throw new Error('Resume not found or unauthorized');
  }
  
  return mapResumeRow(result.rows[0]);
}

/**
 * Get resume history for a user
 * @param {string} userId - User UUID
 * @returns {Promise<Array>} Array of resume objects
 */
export async function getResumeHistory(userId) {
  const result = await query(
    `SELECT * FROM resumes 
    WHERE user_id = $1
    ORDER BY created_at DESC`,
    [userId]
  );
  
  return result.rows.map(mapResumeRow);
}

/**
 * Auto-generate resume from user data
 * @param {string} userId - User UUID
 * @returns {Promise<Object>} Generated resume object
 */
export async function generateResume(userId) {
  const client = await getClient();
  
  try {
    await client.query('BEGIN');
    
    // Get user profile
    const userResult = await query(
      `SELECT 
        id, first_name, last_name, email, phone, bio,
        skill, avatar_url
      FROM users
      WHERE id = $1`,
      [userId]
    );
    
    if (userResult.rows.length === 0) {
      throw new Error('User not found');
    }
    
    const user = userResult.rows[0];
    
    // Get completed courses
    const coursesResult = await query(
      `SELECT 
        c.id, c.title, c.description,
        ce.completed_at, ce.progress_percentage
      FROM course_enrollments ce
      INNER JOIN courses c ON ce.course_id = c.id
      WHERE ce.user_id = $1 AND ce.enrollment_status = 'completed'
      ORDER BY ce.completed_at DESC`,
      [userId]
    );
    
    // Get completed assignments/projects
    const assignmentsResult = await query(
      `SELECT 
        ca.id, ca.title, ca.description,
        as.submitted_at, as.status
      FROM assignment_submissions as
      INNER JOIN course_assignments ca ON as.assignment_id = ca.id
      WHERE as.user_id = $1 AND as.status IN ('submitted', 'graded')
      ORDER BY as.submitted_at DESC
      LIMIT 10`,
      [userId]
    ).catch(() => ({ rows: [] }));
    
    // Get certificates (join with courses table to get title)
    const certificatesResult = await query(
      `SELECT 
        cert.id, 
        c.title, 
        cert.issued_at, 
        cert.certificate_url,
        'Course Completion' as issuer
      FROM certificates cert
      INNER JOIN courses c ON cert.course_id = c.id
      WHERE cert.user_id = $1
      ORDER BY cert.issued_at DESC`,
      [userId]
    ).catch(() => ({ rows: [] }));
    
    // Build resume data structure
    const resumeData = {
      personalInfo: {
        firstName: user.first_name || '',
        lastName: user.last_name || '',
        email: user.email || '',
        phone: user.phone || '',
        bio: user.bio || '',
        avatarUrl: user.avatar_url || null
      },
      education: [],
      skills: user.skill ? [user.skill] : [],
      experience: [], // Manual entry, can be populated from assignments if needed
      projects: assignmentsResult.rows.map(assignment => ({
        id: assignment.id,
        title: assignment.title,
        description: assignment.description,
        completedAt: assignment.submitted_at
      })),
      courses: coursesResult.rows.map(course => ({
        id: course.id,
        title: course.title,
        description: course.description,
        completedAt: course.completed_at,
        progress: parseFloat(course.progress_percentage)
      })),
      certificates: certificatesResult.rows.map(cert => ({
        id: cert.id,
        title: cert.title,
        issuedAt: cert.issued_at,
        issuer: cert.issuer || 'Course Completion',
        certificateUrl: cert.certificate_url
      })),
      achievements: [] // Can be populated from gamification system
    };
    
    // Create resume
    const resume = await upsertResume(userId, {
      templateId: 'modern',
      resumeData: resumeData,
      isAutoGenerated: true
    });
    
    await client.query('COMMIT');
    
    return resume;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

/**
 * Map database row to resume object
 * @param {Object} row - Database row
 * @returns {Object} Mapped resume object
 */
function mapResumeRow(row) {
  return {
    id: row.id,
    userId: row.user_id,
    templateId: row.template_id,
    resumeData: typeof row.resume_data === 'string' 
      ? JSON.parse(row.resume_data) 
      : row.resume_data,
    isAutoGenerated: row.is_auto_generated,
    isActive: row.is_active,
    version: parseInt(row.version),
    generatedAt: row.generated_at,
    lastModifiedAt: row.last_modified_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}
